// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"github.com/swaggo/swag"
	"os"
)

func init() {
	var b, _ = os.ReadFile("./docs/swagger.json") // just pass the file name

	var doc = string(b) // convert content to a 'string'

	// SwaggerInfo holds exported Swagger Info so clients can modify it
	var SwaggerInfo = &swag.Spec{
		Version:          "",
		Host:             "",
		BasePath:         "",
		Schemes:          []string{},
		Title:            "",
		Description:      "",
		InfoInstanceName: "swagger",
		//SwaggerTemplate:  docTemplate,
		SwaggerTemplate: doc,
	}
	//fmt.Println("b", b)
	//fmt.Println("doc", doc)
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
