swagger: "2.0"
openapi: 3.0.0
info:
  title: HMS-Backend
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: Auth
  - name: CRUD Patients
paths:
  /v1/login:
    post:
      tags:
        - Auth
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: admin
                password: admin123
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v1/signup:
    post:
      tags:
        - Auth
      summary: Signup
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: testing
                license_number: '123123'
                username: admin
                password: admin123
                role_id: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v1/create:
    post:
      tags:
        - CRUD Patients
      summary: Create Patient
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                Nik: '12341234'
                Name: John Doe john
                Gender: 2
                Address: Bekasi
                MaritalStatus: 2
                ReligionID: 2
                StatusID: 2
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}