name: cd hms
on:
  push:
    branches:
      - "master"
jobs:
  testing:
    runs-on: ubuntu-latest
    name: "unit testing"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: run unit test
        run: go test -v ./...
      - name: run linting
        uses: golangci/golangci-lint-action@v3

  deploy:
    runs-on: ubuntu-latest
    name: "deploy job"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: abdil12/hospital_mng

      - name: update aws instance
        uses: appleboy/ssh-action@master
        with:
          host: ec2-18-142-246-127.ap-southeast-1.compute.amazonaws.com
          username: ubuntu
          key: ${{ secrets.AWS_KEY }}
          port: 22
          script: |
            sudo docker stop app
            sudo docker container rm app
            sudo docker pull abdil12/hospital_mng
            sudo docker run -d -v $PWD/.env:/.env -p 80:8080 --name app abdil12/hospital_mng